### PR TITLE
[GestureManager 3.8.9 & 3.9.0] Releases~

### PR DESCRIPTION
**Pull request by BlackStartx**
# Change-Log

I'll post here the same change-log from the official release~ ♥

### [Animator Play Audio!]

This version adds the support for the new state behavior: **Animator Play Audio**!

---

 ### We Also Have:
 ###### - [CODE] Typo fix and code cleanup~
 ###### - [CODE] Unity 2022 & C# 9.0 syntax~
 ###### - [CODE] Some small namespace changes~

 ## New Stuff in 3.8.9

### [Settings: Initial Pose!]

You can now chose and save an intial pose to start your simulation with!

Useful when creating props so they are not clipping with your body!

### [Parameter Coercion!]

The simulation should now properly convert and apply different type of values trough your animators correctly.

This should mimic the way VRChat handles this behaviour.

### [Warning: Editor Pause!]

A new warning to warn users that the Editor is paused and the animation will not work.

This caused a lot of confusion, so I guess a warning may help!

### [Debug Mode: State informations!]

The debug mode now shows the same information as the in-game debug window!

This should allow for easier debugging sessions!

---

 ### We Also Have:
 ###### - [FIX] No more error when leaving play-mode and unloading controllers~
 ###### - [CODE] Better warning handling~
 ###### - [CODE] Parameters Cleanup: No more old stuff~ :3
 ###### - [CODE] Moved methods around for more code readability~

 ## [How to use?]
For any information on how to use this tool you can check the ReadMe in the repository page~ ♥

### Thanks to everyone at VRChat team~ ^-^
 - BlackStartx

### CODE REVIEW

**Comment by BluWizard10** [comment]
@momo-the-monster Before you merge, wait for @BlackStartx to add 3.9.0 to this PR since that got released at the same time as well.

**Comment by BlackStartx** [comment]
I've added the commit to also merge the 3.9.0 version of my tool! ^-^ ✨

**Comment by AraHaan** [comment]
Can someone please merge this in? I need to update to this ASAP on VCC.

**Review by momo-the-monster — APPROVED** [review]
Both updates are approved!

**Comment by AraHaan** [comment]
Thanks @momo-the-monster.

**Pull request merged**
