### PR TITLE
Add Av3 emulator

### PR DESCRIPTION
**Pull request by jellejurre**

### CODE REVIEW

**Comment by momo-the-monster** [comment]
Good news! Our security team finished their review and found no blocking issues. They did find the following things, which I'm passing along to you for consideration. Let me know if you'd like to make any changes, or if you'd like us to merge in your PR adding the package to the Curated Listing as-is.


## Editor\LyumaAv3EditorSupport.cs

```
/*103:*/	Camera[] cameras = new Camera[255];
/*104:*/	Camera.GetAllCameras(cameras);
```

This should be more like: `Camera[] cameras = new Camera[Camera.allCamerasCount];` 
Note that GetAllCameras() will throw an Argument Exception if camera array is too small for cameras in scene.

ref: https://docs.unity3d.com/ScriptReference/Camera.GetAllCameras.html

## Runtime\Scripts\A3EOSCConfiguration.cs

```
/*???:*/	System.IO.Path.Combine() 
```

The Combine() function does not compensate for directory traversal and relies on System.IO.File and System.IO.Directory classes to handle traversal, which they do not do universally.

```
/*128:*/	return JsonUtility.FromJson<OuterJson>(System.IO.File.ReadAllText(full_file_path));

/*132:*/	System.IO.File.WriteAllLines(filename, System.Text.RegularExpressions.Regex.Replace("\ufeff" +

/*162:*/	System.IO.Directory.CreateDirectory(vrcOSCPath);

/*170:*/	foreach (string file in System.IO.Directory.GetDirectories(vrcOSCPath, "*", System.IO.SearchOption.TopDirectoryOnly)) {

/*172:*/	DateTime thisdt = System.IO.File.GetLastWriteTime(file);

/*187:*/	System.IO.Directory.CreateDirectory(avatarDirectory);
```

These functions do not compensate for directory traversal. While this is a small issue in the current implementation, it is unclear if future feature enhancements might be a problem.

## Runtime\Scripts\A3ESimpleOSC.cs

```
/*597:*/	byte[]scratchSpace = new byte[8192];
```

Not sure if this is arbitrary or not. If not, consider defining this for reference/use later.

```
/*660:*/	buffer = scratchSpace;

/*663:*/	EncodeOSCInto(buffer, ref encodedLength, msg);
/*676:*/	EncodeOSCBundleInto(buffer, ref encodedLength, messages, ts);
```

scratchSpace is handed off to two functions, ultimately landing in EncodeOSInto().

```
/*479:*/  public static void EncodeOSCInto(byte[] data, ref int offset, OSCMessage msg, string type_tag_override="") {

/*485:*/	byte[] tmp = System.Text.Encoding.UTF8.GetBytes((string)msg.path);
/*486:*/	Array.Copy(tmp, 0, data, offset, tmp.Length);
/*487:*/	data[tmp.Length + offset] = 0;
/*488:*/	offset += tmp.Length;

/*492:*/	tmp = System.Text.Encoding.UTF8.GetBytes((string)msg.typeTag);
/*493:*/	Array.Copy(tmp, 0, data, offset, tmp.Length);
/*494:*/	data[tmp.Length + offset] = 0;
/*495:*/	offset += tmp.Length;
```

Here, msg.path and msg.typeTag can be a string of any size, so GetBytes() can return larger than 8192. If `tmp.Length > data.Length`, Array.Copy() with throw an Argument Exception. Using a different strategy here for a scratch buffer is recommended.

ref: https://learn.microsoft.com/en-us/dotnet/api/system.array.copy

## Runtime\Scripts\LyumaAv3Osc.cs

```
/*41:*/	        byte[] oscBuffer = new byte[65535];
```

Could this be handled with `ushort.MaxValue`? 

```
/*177:*/	receiver.SendOSCPacket(message, oscBuffer);
```

oscBuffer is sent to SendOSCPacket from Runtime\Scripts\A3ESimpleOSC.cs. This buffer is a size mismatch for the scratch buffer used in A3ESimpleOSC.cs and might cause issues. Dynamic buffer sizes or strict management of incoming data combined with stronger exception handling is recommended.

**Comment by jellejurre** [comment]
Hello, thanks for the response. 

Right now we have quite some changes in the pipeline as well, we're hoping in the next few days to release an update with those changes, and we'll also have a look at the feedback and integrate changes based on that in that release. I'll update the MR with the new release when it's ready, and once that's done, we'd like for it to be added to the curated listing.

**Comment by lyuma** [comment]
We released an update in 3.2.0 and modified our version `com.vrchat.avatars` dependency to be `>=3.1.0 <3.3.0`

jellejurre incorporated most of the feedback from the code review. This pull request has been updated to version 3.2.0 but I think we're ready to go.

We did not yet address the feedback related to `System.IO.Path.Combine`, so I opened an issue to keep track of this but it was labeled a small issue and not a blocker.

**Comment by jellejurre** [comment]
Implemented the camera and buffer fixes at https://github.com/lyuma/Av3Emulator/commit/857ebb23060e709f8d559b03c4cdd173b0e96322

We just released a new version, and we'd like this version to be put in the curated listing

**Comment by momo-the-monster** [comment]
@jellejurre - thanks for the update. I can confirm that there are no new issues introduced in this version from a security perspective. However, I noticed that both submitted versions need small changes to their ZIP files - the package contents should be directly in the root of the zip instead of inside a folder like `Av3Emulator-3.1.3`, the current format won't work with the VCC.

**Comment by jellejurre** [comment]
Ah, thanks for notifying us, @momo-the-monster we replaced the zips in place, links should link to the correctly formatted zips now

**Comment by momo-the-monster** [comment]
@jellejurre - confirmed, the zips look good now - thanks.

**Comment by momo-the-monster** [comment]
Just doing some final testing, we should be able to merge this within the next few days!

**Review by momo-the-monster — APPROVED** [review]

**Pull request merged**
