### PR TITLE
release Av3Emulator 3.4.3

### PR DESCRIPTION
**Pull request by lyuma**
bugfix for setting custom float inputs (such as OSC) from the inspector. added some missing package.json properties
fix "author" field in package.json
add compatibility with newer versions of GestureManager
CC @jellejurre

### CODE REVIEW

**Comment by jellejurre** [comment]
@momo-the-monster sorry for the ping, but the version on curated now doesn't work well with the latest gesturemanager so we'd like for this to be looked over sometime soon if possible

**Comment by momo-the-monster** [comment]
We'll take a look this week!

**Comment by momo-the-monster** [comment]
Security review passed. We did find one _tiny_ usability issue to discuss before merging.

The latest version triggers three warnings about using an Obsolete function:

```
Packages\lyuma.av3emulator\Editor\LyumaAv3EditorSupport.cs(119,5): warning CS0618: 'CompilationPipeline.assemblyCompilationStarted' is obsolete: 'Use compilationStarted, compilationFinished or assemblyCompilationFinished instead. Note that using any of these functions to do time measurements is a bad idea as they run async to actual compilation.'
```
The same warning is issued for lines 120 and 225 in the same file. This is not a blocker for release - how would you like to handle it @lyuma @jellejurre?

**Comment by jellejurre** [comment]
> Security review passed. We did find one _tiny_ usability issue to discuss before merging.
> 
> The latest version triggers three warnings about using an Obsolete function:
> 
> ```
> Packages\lyuma.av3emulator\Editor\LyumaAv3EditorSupport.cs(119,5): warning CS0618: 'CompilationPipeline.assemblyCompilationStarted' is obsolete: 'Use compilationStarted, compilationFinished or assemblyCompilationFinished instead. Note that using any of these functions to do time measurements is a bad idea as they run async to actual compilation.'
> ```
> 
> The same warning is issued for lines 120 and 225 in the same file. This is not a blocker for release - how would you like to handle it @lyuma @jellejurre?

Thanks for letting us know. We will look into fixing this next update, but I don't think this is a blocker indeed. If possible you can go ahead with the merge

**Pull request merged**
