### PR TITLE
Add `AAO: Avatar Optimizer` v1.7.7 and `NDMF` v1.4.1

### PR DESCRIPTION
**Pull request by anatawa12**
This PR adds [AAO: Avatar Optimizer](https://vpm.anatawa12.com/avatar-optimizer/) v1.7.7, an Avatar Optimization Utility and [NDMF](https://ndmf.nadena.dev/) v1.4.1, which is dependencies of AAO: Avatar Optimizer.

AAO is a set of non-destructive avatar optimization utilities with 13 components.

The main feature of AAO is [AAO Trace and Optimize](https://vpm.anatawa12.com/avatar-optimizer/en/docs/reference/trace-and-optimize/) component, which optimizes avatar **without** affecting avatars behavior.

### CODE REVIEW

**Comment by bdunderscore** [comment]
I'm a little concerned this might trigger https://github.com/vrchat-community/creator-companion/issues/369 and prevent upgrades from being visible even when the upstream repo is added...

**Comment by BluWizard10** [comment]
I personally do not believe this would be necessary to have as a Curated Package. Because one, it is a LONG and LENGTHY process to push a new update to the Curated Listing. Secondly, you will need to be okay with the fact most people would be stuck with older versions before the newer version is even approved (which could take days or even a month!).

So I see no benefit whatsoever putting this as Curated. It's better to keep it as a Community Repository, because YOU have more control over that than a Curated Listing. That's just my opinion.

**Comment by anatawa12** [comment]
I know adding package to curated is extremely slow so I'm planned to push releases to curated after several patch releases and no (serious) bug reports for several weeks.

**Comment by momo-the-monster** [comment]
Thank you for the PR and suggestion of these packages, but VRChat is not currently accepting new curated packages. I hope we can review and clarify our policy and process around curated packages.

**Pull request closed without merging**
